### ISSUE TITLE
Interactivity Lock graphic toggled incorrectly at startup

### ISSUE THREAD

**Issue by orrblue** [Wisc-HCI/simple-vp#1]
The lock graphic should be shown as unlocked when opening the webapp, as the content is interactable 
<img width="185" alt="image" src="https://user-images.githubusercontent.com/11370512/154353079-c962cd7c-be6c-4781-baf3-54e9230f21b6.png">

**Comment by AndrewJSchoen** [comment]
Currently we aren't doing anything with that toggle, but it should probably be handled. I added this to the set of possible enhancements.

**Comment by orrblue** [comment]
This issue appears to be resolved.
