### ISSUE TITLE
Firefox on MacOS Hat and Boot placement issue

### ISSUE THREAD

**Issue by orrblue** [Wisc-HCI/simple-vp#2]
Hi, just another thing I noticed is that there is an issue when I use Firefox on MacOS Monterey. Not sure if you intend to support firefox, but here's a video clip of the bug when I try placing a hat or boot into their slots.

https://user-images.githubusercontent.com/11370512/154354634-f2f0d9a5-53b1-40d9-b764-0e45b448e06b.mov

**Comment by AndrewJSchoen** [comment]
Ideally yes, we would like to support Firefox. Are there any helpful log messages/errors that get printed out when this occurs on your setup?

**Comment by orrblue** [comment]
Sorry for the late reply. First, upon loading the full screen app (before drag and dropping the hat), I get the following errors. Not sure how to copy and paste them, but I can look into it. Also, I don't know why it says chrome next to some of the errors, but I'm still using firefox.

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/11370512/167515991-c8e19246-9408-469f-826a-255dcb7a0697.png">

I then try to drag and drop the sombrero as well as the boots, as is shown in the video, but the same thing as in the video happens. I do not see additional errors or warning pop up in the console or developer tools panel since loading the page (image above)
